/** Mirrors backend REQUEST_ERROR_CODES */
export const REQUEST_ERROR_CODES = {
  LISTING_NOT_AVAILABLE: 'LISTING_NOT_AVAILABLE',
  LISTING_NOT_ACCEPTING: 'LISTING_NOT_ACCEPTING',
  REQUEST_ALREADY_EXISTS: 'REQUEST_ALREADY_EXISTS',
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_ALREADY_HANDLED: 'REQUEST_ALREADY_HANDLED',
  LISTING_NOT_ACCEPTING_REQUESTS: 'LISTING_NOT_ACCEPTING_REQUESTS',
} as const
