/** Mirrors backend REQUEST_ERROR_CODES */
export const REQUEST_ERROR_CODES = {
  LISTING_NOT_AVAILABLE: 'LISTING_NOT_AVAILABLE',
  LISTING_NOT_ACCEPTING: 'LISTING_NOT_ACCEPTING',
  REQUEST_ALREADY_EXISTS: 'REQUEST_ALREADY_EXISTS',
} as const
