import { SUPPORT_EMAIL } from '../constants/support'

export const exportContent = {
  brandName: 'Sangira',
  nullLabel: '—',
  naLabel: 'N/A',
  generatedOn: (dateLabel: string) => `Generated by Sangira on ${dateLabel}`,
  generatedOnWithEmail: (dateLabel: string) =>
    `Generated by Sangira on ${dateLabel} · ${SUPPORT_EMAIL}`,
  allTime: 'All-time',
  toast: {
    donorPdf: {
      loading: 'Generating impact summary…',
      success: 'Impact summary downloaded.',
      error: 'Could not generate the impact summary.',
    },
    adminCsv: {
      loading: 'Exporting reports…',
      success: 'Reports CSV downloaded.',
      error: 'Could not export reports.',
    },
    adminPdf: {
      loading: 'Generating platform report…',
      success: 'Platform report downloaded.',
      error: 'Could not generate the platform report.',
    },
  },
  donorPdf: {
    documentTitle: 'Impact Summary',
    verifiedSince: (monthYear: string) => `Verified donor since ${monthYear}`,
    stats: {
      meals: 'Meals redistributed',
      mealsThisMonth: (count: number) => `+${count.toLocaleString()} this month`,
      waste: 'Waste prevented',
      wasteThisMonth: (kg: number) => `+${kg.toLocaleString()} kg this month`,
      transfers: 'Completed transfers',
      ngosServed: 'NGOs served',
    },
    monthlyTable: {
      title: 'Monthly breakdown',
      headers: ['Month', 'Meals'],
      empty: 'No monthly data recorded yet.',
    },
  },
  adminPdf: {
    documentTitle: 'Platform Report',
    stats: {
      meals: 'Meals redistributed',
      mealsMom: 'MoM change',
      waste: 'Waste prevented',
      transfers: 'Completed transfers',
      avgMatchTime: (days: number) => `Avg match time (last ${days} days)`,
    },
    tables: {
      mealsByDay: {
        title: 'Meals by day of week',
        headers: ['Day', 'Meals'],
      },
      foodType: {
        title: 'Listings by food type',
        headers: ['Food type', 'Listings'],
        empty: 'No listings yet.',
      },
      topDonors: {
        title: 'Top donors',
        headers: ['Organisation', 'Transfers'],
        empty: 'No completed transfers yet.',
      },
      topNgos: {
        title: 'Most served NGOs',
        headers: ['Organisation', 'Pickups'],
        empty: 'No completed pickups yet.',
      },
    },
  },
  adminCsv: {
    sections: {
      stats: 'Platform stats',
      mealsByDay: 'Meals by day of week',
      foodType: 'Listings by food type',
      topDonors: 'Top donors',
      topNgos: 'Most served NGOs',
    },
    columns: {
      metric: 'Metric',
      value: 'Value',
      day: 'Day',
      meals: 'Meals',
      foodType: 'Food type',
      count: 'Count',
      organisation: 'Organisation',
      transfers: 'Transfers',
      pickups: 'Pickups',
    },
    stats: {
      mealsTotal: 'Meals redistributed (total)',
      mealsMom: 'Meals month-over-month change (%)',
      wasteKg: 'Waste prevented (kg)',
      completedTransfers: 'Completed transfers',
      avgMatchTime: 'Average match time (minutes)',
      avgMatchTimeWindow: 'Average match time window (days)',
    },
  },
  filenames: {
    donorImpact: (orgSlug: string, monthStamp: string) =>
      `sangira-impact-${orgSlug}-${monthStamp}.pdf`,
    adminReportsCsv: (dateStamp: string) => `sangira-reports-${dateStamp}.csv`,
    adminReportsPdf: (dateStamp: string) =>
      `sangira-platform-report-${dateStamp}.pdf`,
  },
  disabledNoData: 'No data available to export yet.',
} as const
